version: '3.9'

networks:
  redis_network:
    name: reseau_redis
  rabbitmq_network:
    name: reseau_rabbitmq
  sql_network:
    name: reseau_sql
  web_network:
    name: reseau_web

services:

  # #############################################################################
  # WEB CONTAINER                                                               #
  # #############################################################################
  web:
    image: image_web:latest
    build:
      context: ./
      dockerfile: Web/Dockerfile
    ports: 
      - 8080:80
    container_name: web_container
    depends_on:
      - user.data
      - rabbitmq
      - sql.data      
      - applicants.api
      - service-api-identity
      - service-api-jobs
    networks:
      - web_network

  # #############################################################################
  # SERVICE-IDENTITY-API CONTAINER                                              #
  # #############################################################################
  service-api-identity:
    image: mockingbird050/identity-api:v1
    build:
      context: ./
      dockerfile: Services/Identity.Api/Dockerfile
    environment:
      - RedisHost=user.data:6379
      - HostRabbitmq=rabbitmq
    ports: 
      - 8084:80
    container_name: service-api-identity
    networks:
      - redis_network
      - rabbitmq_network
      - sql_network
      - web_network
    depends_on:
      - user.data
      - rabbitmq   

  # #############################################################################
  # SERVICE-JOBS-API CONTAINER                                                  #
  # #############################################################################
  service-api-jobs:
    image: mockingbird050/job-api:v1
    build:
      context: ./
      dockerfile: Services/Jobs.Api/Dockerfile
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
      - HostRabbitmq=rabbitmq 
    ports: 
      - 8083:80
    container_name: service-api-jobs
    networks:
      - redis_network
      - rabbitmq_network
      - sql_network
      - web_network
    depends_on:
      - sql.data
      - rabbitmq

  # #############################################################################
  # SERVICE-APPLICANTS-API CONTAINER                                            #
  # #############################################################################
  applicants.api:
    image: mockingbird050/applicants-api:v1
    build:
      context: ./
      dockerfile: Services/Applicants.Api/Dockerfile
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;
      - HostRabbitmq=rabbitmq
    ports: 
      - 8081:80
    container_name: applicants.api
    networks:
      - redis_network
      - rabbitmq_network
      - sql_network
      - web_network
    depends_on:
      - rabbitmq
      - sql.data

  # #############################################################################
  # SQL SERVER                                                                  #
  # #############################################################################
  sql.data:
    image: image_database:latest
    build:
      context: ./Database
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass@word
    ports:
      - 1433:1433
    container_name: sqlServer_container
    networks:
      - sql_network
    volumes:
      - /home/mockingbird/Desktop/Cours/Ynov/M2-2022-2023/Docker/elec2/projet/appscore/Database:/var/lib/Database

  # #############################################################################
  # RABBITMQ CONTAINER                                                          #
  # #############################################################################
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_container
    networks:
      - rabbitmq_network
    depends_on:
      - sql.data
      - user.data

  # #############################################################################
  # REDIS CONTAINER                                                             #
  # #############################################################################
  user.data:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - redis_network
    container_name: redis_container

  # #############################################################################